#!usr/bin/python3

col_list=["blue", "Columbus"]

col_list.append("1492")
input("What is your name?")
print("In " [col_list[2]] [col_list[1]] "sailed the ocean" [col_list[0]]". input "fell off the boat.)
 
